[project]
name = "rag-deployment"
version = "0.1.0"
description = "Simple Pythonic RAG App"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit==2.0.4",
    "numpy==2.2.2",
    "pypdf2==3.0.1",
    "websockets==14.2",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.0",
    "nump>=5.5.5.5",
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "python-dotenv>=1.0.1",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.1",
     "arxiv==2.1.3",
    "duckduckgo-search==5.3.1b1",
    "langchain>=0.1.20",
    "langchain-community>=0.0.30",
    "langchain-openai==0.3.2",
    "langgraph==0.2.67",
    "langchain-core==0.3.31",
    "langchain-qdrant==0.2.0",
    "qdrant-client>=1.10.1",
    "tiktoken>=0.8.0",
    "pymupdf==1.25.2",
    "langsmith==0.3.1",
    "openai==1.60.0",
    "cohere==5.13.11",
    "lxml==5.3.0",
    "bs4==0.0.2",
    "pydantic==2.10.0",
    "grandalf>=0.8",
    "pypdf==4.0.1",
]

